version: '3.8'

services:
  php:
    build: 
      context: .  # 현재 디렉토리에서 Dockerfile을 사용하여 빌드
    container_name: php-service
    volumes:
      - ./:/var/www/html # registration-page 디렉토리 자체를 웹 루트로 설정
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "8080:80" # 로컬 8080 포트를 컨테이너 80 포트에 매핑
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx 설정 파일 마운트
      - ./:/var/www/html # registration-page 디렉토리 자체를 웹 루트로 설정
    networks:
      - app-network

networks:
  app-network:

